### ISSUE TITLE
Error on compilation styles.xml

### ISSUE THREAD

**Issue by nminaya** [enusbaum/XamariNES#1]
I'm getting the following errors:
![image](https://user-images.githubusercontent.com/7952888/63389460-c2e8b300-c379-11e9-94a9-b29924361fff.png)
 
I'm trying to run the Android app from master branch.

**Comment by enusbaum** [comment]
Hey there!

Xamarin errors can sometimes be a little... hard to troubleshoot. For this one, the project targets API 28 (Pie), so ensure you have the correct SDK installed:

![image](https://user-images.githubusercontent.com/1139047/63395391-8aed6a00-c391-11e9-9055-f747a7b29acf.png)

If you have 9.0 installed, do a Clean and Rebuild on the solution and let me know how that works out.

**Comment by nminaya** [comment]
I did the first build having Android 27. Then I downloaded Android 28 and here I was having the error with styles.xml file.

After a clean and rebuild the error disappeard.

Thanks.
